### PR TITLE
Decouple asset loading logic from Localization

### PR DESCRIPTION
**Pull request by spiritinlife**
Library shouldn't make assumptions about asset loading. For example the recent `useDocumentStorage` shouldn't be added as an option to EasyLocalizationDelegate since its very specific. Allowing the developer to bring their own asset loading logic is the only way to proceed safely.

We provide a default asset loader RootBundleAssetLoader and allow the developer to override this default. By doing this we also remove http dependency and the `loadPath` if/else logic.
In the example, I have provided asset loaders for Network, File, String, Testing and more can be added.

This also allows developers to do integration testing in their apps since this bug flutter/flutter#44182 right now is an issue for flutter_driver.

### CODE REVIEW

**Comment by spiritinlife** [comment]
@danilofuchs We could also just expose `load` as function on the `LocalizationDelegate` instead of a class, wasn't sure whats best for this.

**Comment by spiritinlife** [comment]
@aissat @danilofuchs Loosing the dependency on rootBundle allows us to unit test `localization.dart`.
I have added some initial tests, take a look.
This could be a start for this https://github.com/aissat/easy_localization/issues/34

**Comment by aissat** [comment]
hi guys this great work, I agree with all code  but I have a suggestion to make this code more simple and easy  
 - we must hide this code from `main.dart`
``` dart
class StringAssetLoader extends AssetLoader {
  @override
  Future<String> load(String localePath) {
    return Future.value('''{"title" : "Hello"}''');
  }
}

class FileAssetLoader extends AssetLoader {
  @override
  Future<String> load(String localePath) {
    File file = File(localePath);
    return file.readAsString();
  }
}

class NetworkAssetLoader extends AssetLoader {
  @override
  Future<String> load(String localePath) async {
    String url =
        "https://raw.githubusercontent.com/aissat/easy_localization/master/example/$localePath";
    return http.get(url).then((response) => response.body.toString());
  }
}

// asset loader to be used when doing integration tests
// default AssetLoader suffers from this issue
// https://github.com/flutter/flutter/issues/44182
class TestsAssetLoader extends AssetLoader {
  @override
  Future<String> load(String localePath) async {
    final ByteData byteData = await rootBundle.load(localePath);
    return utf8.decode(byteData.buffer.asUint8List());
  }
}
```
i mean i'll make this in `easy_localization` PKG with keep others customizable
example :
``` dart
import 'package:path_provider/path_provider.dart';
class FileProvidertLoade extends AssetLoader {
  @override
  Future<String> load(String localePath) {
       Directory appDocDir = await getApplicationDocumentsDirectory();
       String appDocPath = appDocDir.path+"localePath";
      .......
  }
}
```

**Comment by spiritinlife** [comment]
@aissat agree on this.
Maybe these AssetLoaders should be given as examples in `Readme.md`

**Comment by aissat** [comment]
@spiritinlife look last update

**Comment by aissat** [comment]
> @aissat @danilofuchs Loosing the dependency on rootBundle allows us to unit test `localization.dart`.
> I have added some initial tests, take a look.
> This could be a start for this #34

thanks, @spiritinlife that's great work :+1:  :100:

**Comment by spiritinlife** [comment]
@aissat Thank you for your feedback and your awesome work. I checked your latest commits and added some comments.
I don't fully agree but i am ok with it :)
The gist of comments is that we shouldn't provide any AssetLoader apart from RootBundleAssetLoader and we should drop the dependency to http since its unrelated to the package.

Example AssetLoaders should be provided in Readme so that the user knows how to proceed.
Also loadPath is very specific to NetworkAssetLoader and does not serve any other purpose, thus imho it should be removed completely.
Localization should get the Locale and the base resources path and call load with the proper localePath.

**Comment by aissat** [comment]
@spiritinlife I agree with u about `NetworkAssetLoader` and `StringAssetLoader` very logical

**Pull request merged**
