### PR TITLE
PR dev-bloc

### PR DESCRIPTION
**Pull request by Overman775**
- tweks
- clean
- fix tests
- check required params
- update pub
- preloaderColor

### CODE REVIEW

**Comment by Overman775** [comment]
@aissat About stream.broadcast()... its bad way to use for one listener/transform, but i can't fix this, hot reload send error mesages 😕

**Comment by aissat** [comment]
I have suggestions to make this for all PKG

**Comment by Overman775** [comment]
> I have suggestions to make this for all PKG

What exactly do you want to do?

**Comment by aissat** [comment]
> @aissat About stream.broadcast()... its bad way to use for one listener/transform, but i can't fix this, hot reload send error mesages confused

**Comment by aissat** [comment]
> > I have suggestions to make this for all PKG
> 
> What exactly do you want to do?

@Overman775  check #103

**Comment by aissat** [comment]
> @aissat About stream.broadcast()... its bad way to use for one listener/transform, but i can't fix this, hot reload send error messages confused

wat i want to do :
- fixed #103  coz `_translations=null` by using Stream 
file `lib/src/localization.dart`
`final String resource = this._translations.get(key);`

```dart
if (await assetLoader.localeExists(localePath) == true) {
      Map<String, dynamic> data = await assetLoader.load(localePath);
      instance._translations = Translations(data);
      return true;
    }
```
- added  Handle File load errors in widget error like this

Simulator Screen Shot - iPhone 11 Pro Max - 2020-03-22 at 20 30 36

**Comment by Overman775** [comment]
> @Overman775 check #103

Yes, I see a problem when the resource loader does not finish loading the `text ("company_name" .tr ())` tries to get the translation, but return null.

I think the flickering text and this bug it is same

**Comment by aissat** [comment]
> > @Overman775 check #103
> 
> Yes, I see a problem when the resource loader does not finish loading the `text ("company_name" .tr ())` tries to get the translation, but return null.
> 
> I think the flickering text and this bug it is same

@Overman775  check this part 
`_translations=null` by using Stream 
file `lib/src/localization.dart`
`final String resource = this._translations.get(key);`

```dart
if (await assetLoader.localeExists(localePath) == true) {
      Map<String, dynamic> data = await assetLoader.load(localePath);
      instance._translations = Translations(data);
      return true;
    }
```

**Comment by Overman775** [comment]
Problem in final `String resource = this._translations.get(key);`

we are try get(key) BUT this._translations = null at this moment...Yep

```
if (await assetLoader.localeExists(localePath) == true) {
      Map<String, dynamic> data = await assetLoader.load(localePath);
      instance._translations = Translations(data);
      return true;
      assetLoadedStream.sink.add(true) <--- send strim like done or error
    }
```
Use **StreamZip** from https://pub.dev/packages/async#-readme-tab-
```
  @override
  Widget build(BuildContext context) {
    return Container(
      color: widget.preloaderColor,
      child: StreamBuilder(
          stream: StreamZip([bloc.outStream, assetLoadedStream]),
          builder: (context, snapshot) {
```

This is a theory 🤔

**Comment by aissat** [comment]
> Problem in final `String resource = this._translations.get(key);`
> 
> we are try get(key) BUT this._translations = null at this moment...Yep
> 
> ```
> if (await assetLoader.localeExists(localePath) == true) {
>       Map<String, dynamic> data = await assetLoader.load(localePath);
>       instance._translations = Translations(data);
>       return true;
>       assetLoadedStream.sink.add(true) <--- send strim like done or error
>     }
> ```
> 
> Use **StreamZip** from https://pub.dev/packages/async#-readme-tab-
> 
> ```
>   @override
>   Widget build(BuildContext context) {
>     return Container(
>       color: widget.preloaderColor,
>       child: StreamBuilder(
>           stream: StreamZip([bloc.outStream, assetLoadedStream]),
>           builder: (context, snapshot) {
> ```
> 
> @aissat This is a theory 🤔

@Overman775 nice :) my idea something like this:

``` dart
  final validate = StreamTransformer<Locale, Locale>.fromHandlers(
      handleData: (locale, sink) async {
    if (locale != null ) {
      await _init();
      log('easy localization:  init() ');
      sink.add(locale);
    } else if( !assetLoader.isLoade ){
      sink.addError("assetLoader error ");
      log('easy localization: assetLoader error');
    }else {
      sink.add(locale);

    }
  });
```

**Pull request merged**
