### PR TITLE
Allow base language fallback to continue if the base language asset is not found

### PR DESCRIPTION
**Pull request by shrdnar**
Bug fix in regards to @Pomis here: https://github.com/aissat/easy_localization/pull/440#issuecomment-1088451882

Prevents the app from crashing if the base language asset file does not exist.

### CODE REVIEW

**Review by aissat — APPROVED** [review]

**Comment by aissat** [comment]
@shrdnar thanks bro, welcome :)

**Comment by naamapps** [comment]
@aissat didn't you mean to merge this instead of closing?

**Comment by aissat** [comment]
> @aissat didn't you mean to merge this instead of closing? 

LoL 😅

**Comment by jgoyvaerts** [comment]
@aissat can you push this as part of a new version please? I need this fix in our app to be able to upgrade to flutter 3.0

**Comment by aissat** [comment]
> @aissat can you push this as part of a new version please? I need this fix in our app to be able to upgrade to flutter 3.0

@jgoyvaerts done :)

**Comment by jgoyvaerts** [comment]
@aissat Thank you!

**Pull request merged**
