### PR TITLE
add new Logging package

### PR DESCRIPTION
**Pull request by Overman775**
Ready !)

### CODE REVIEW

**Comment by dftorres** [comment]
Hey man, good idea to have a customizable logging package. But I want to completely disable logging for my project. Do you have any idea in how can I disable logging?

**Comment by Overman775** [comment]
@dftorres only on 3.0 version will be released

**Comment by aissat** [comment]
@Overman775 need fixed some test lol ;)

**Comment by Overman775** [comment]
@aissat  @spiritinlife  all done! Please check this PR

**Comment by spiritinlife** [comment]
@Overman775 @aissat Why do we want to include a custom logger in easy localization?

I am not sure i understand the point of this and the Readme is now more confusing because it includes stuff about logging.

I believe easy_logger should be made into a separate library and repository with different tests and coverage.
We can use it as a dependency inside easy_localization if we want to.

Also there are packages right now that do logging exceptionally good like https://pub.dev/packages/logger and https://pub.dev/packages/simple_logger. Is there something that those packages are missing and easy_logger does it better?
Even if that is the case, i would prefer to support these libraries with a PR.

Lets work as a community and not create duplicate libraries.

**Comment by Overman775** [comment]
@spiritinlife EasyLogger its extarnal package in same repository.  Best way need splitted ptoject to packages, like in aissat branch(easy_localization, easy_localization_loaders, easy_localization_codegen, easy_logger).

We need do this because for big comercial project need another workers with errors and loging, sent to logger service and other, and customers don't like loggin in project, need customosible solution.

I made this package because @aissat don't prefer external packages in project, and if we have own solution it's easy controlled.

**Comment by Overman775** [comment]
@spiritinlife yep, need eddit readme ))

**Comment by Overman775** [comment]
@aissat @spiritinlife  i think need splitted this version project like in this [branch ](https://github.com/aissat/easy_localization/tree/aissat)

**Review by spiritinlife — CHANGES_REQUESTED** [review]
@Overman775 @aissat I understand why we need a customizable logger, and bringing a full external dep might be an overkill, but i would like to restrict the easy_localization Readme for logger to include the usecases that are valid for easy_localization.

1. How to deactivate logging
2. Custom logging for hooking into the messages

Also i am not sure what enableBuildModes does right now. @Overman775 could you explain and maybe add it to the Readme also?

**Comment by aissat** [comment]
hi guys, Nice to have this discussion ، We have to focus on the goal of a library, so I agree with @spiritinlife and  I liked your opinion. It is also important to add a solution for `Logging` like #173  #241  because it is required by some developers,
So we have to solve this problem. I know that there are many libraries that help, but the idea is that we need to reduce the external dependencies @Overman775 
Therefore, the goal of this code is not to reinvent the wheel, but rather a solution and provide a suitable solution

**Comment by Overman775** [comment]
@spiritinlife @aissat we can use this logger in other packages like loaders via a single entry `EasyLocalization.logger`
@aissat i think need make this package external but in this repository

**Comment by aissat** [comment]
@Overman775 I don't like using external PKG coz if we must use external lib, I think it is best to use pkgs that exist, This brings us back to @spiritinlife saying https://github.com/aissat/easy_localization/pull/315#issuecomment-761673662 and What is the benefit of reinventing the wheel.
another thing is we want minimize Dependencies

**Comment by Overman775** [comment]
@spiritinlife added readme for Easy Logger, pleas recheck ;)

**Comment by spiritinlife** [comment]
My suggestion is to only state in Readme the logger use cases that are
valid for easy localization. Like how to turn off the logging messages or
how to only show these category of messages. From the perspective of easy
localization the log levels are irrelevant without any more context.

**Comment by Overman775** [comment]
@spiritinlife looks beter?

**Review by aissat — APPROVED** [review]

**Pull request merged**
