### PR TITLE
[pub] Fix pipeline v2

### PR DESCRIPTION
**Pull request by bw-flagship**
@aissat It seems that I needed to install flutter, not only dart.
Fixed it again. This version of the pipeline is tested in my fork (except the publish-step itself), so I'm optimistic that it will work this time.

### CODE REVIEW

**Comment by aissat** [comment]
@bw-flagship  check this  
https://github.com/dart-lang/setup-dart/blob/main/.github/workflows/publish.yml
Screenshot from 2023-05-14 17-32-16

**Comment by bw-flagship** [comment]
@aissat That won't work for us, because we depend on Flutter, not only on Dart

**Comment by aissat** [comment]
> @aissat That won't work for us, because we depend on Flutter, not only on Dart
> 
> 


we can fix it by 

```yaml
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
```

**Comment by bw-flagship** [comment]
Please check my latest commits, is that what you meant?

**Comment by aissat** [comment]
> Please check my latest commits, is that what you meant?

i think to trigger publish job, we should ignore `if` condition temporary for test it

**Comment by aissat** [comment]
check this https://github.com/aissat/easy_localization/actions/runs/4991187957/jobs/8937339866#step:8:289

**Pull request closed without merging**
