### PR TITLE
[v3] migrating to null safety

### PR DESCRIPTION
**Pull request by aissat**

### CODE REVIEW

**Comment by acoutts** [comment]
Hi there is something wrong on this branch- when a key isn't found, the app hits an exception. In the old lib, if a key wasn't found, it failed silently so it didn't interrupt the app in any unexpected manner.

**Comment by aissat** [comment]
> Hi there is something wrong on this branch- when a key isn't found, the app hits an exception. In the old lib, if a key wasn't found, it failed silently so it didn't interrupt the app in any unexpected manner.
> 
> ```
> Unhandled exception:
> Exception: Cannot cache a key that is not nested.
> #0      Translations.getNested (package:easy_localization/src/translations.dart:24:7)
> #1      Translations.get (package:easy_localization/src/translations.dart:7:27)
> #2      Localization.Eval ()
> #3      Localization._resolve (package:easy_localization/src/localization.dart:171:18)
> ```
> 
> Seems like `isNested()` returns true on keys which aren't found.
> 
> Ahh, so if the string contains a period it's now confused because it thinks it's a nested string key!
> 
> ie: `'Processing...'.tr()` doesn't work with the nested stuff.
> 
> Can we optionally disable nested checks completely? I don't want to use a `foo.bar.baz` key setup, i want to simply use english strings within the app and match it exactly to the json keys.

hi  @acoutts plz more detailed example for this bug

**Comment by acoutts** [comment]
Add this in your json file:

```json
{
  "Please tap the button..": "Please tap the button.."
}
```

Then in your app,

```dart
Text('Please tap the button..'.tr())
```

The key is the lang key should contain a period.

**Comment by aissat** [comment]
> Add this in your json file:
> 
> ```json
> {
>   "Please tap the button..": "Please tap the button.."
> }
> ```
> 
> Then in your app,
> 
> ```dart
> Text('Please tap the button..'.tr())
> ```
> 
> The key is the lang key should contain a period.

I write test case for this 


```dart
      test('instance.tr() ', () {
        expect(Localization.instance.tr('Please tap the button..'), 'Please tap the button..');
      });

      test('tr()', () {
        expect(tr('Please tap the button..'), 'Please tap the button..');
      });

      test('ext tr()', () {
        expect('Please tap the button..'.tr(), 'Please tap the button..');
      });

```
test passed

image

**Comment by acoutts** [comment]
Hm how strange! So how does the nested key logic distinguish between if you are doing `foo.bar.baz` vs `Some full sentence...`?

**Comment by aissat** [comment]
@acoutts  this is some nested case 
https://github.com/aissat/easy_localization/blob/bc8f6dab42471aad703a6e221a304e07d2f10022/test/utils/test_asset_loaders.dart#L33
 https://github.com/aissat/easy_localization/blob/bc8f6dab42471aad703a6e221a304e07d2f10022/test/utils/test_asset_loaders.dart#L48-L57

**Comment by acoutts** [comment]
Ah very cool- thanks for showing! Can you see if having 3 periods breaks it? That's the only difference I found from my app vs the test there.

**Comment by aissat** [comment]
@acoutts check this maybe your issue related to #337  #331 or if u can create an example or test case failed

**Comment by acoutts** [comment]
Thanks! That looks related to my issue.

One other thing, I tried to disable the log messages for tests:
```
  EasyLocalization.logger.enableLevels = <LevelMessages>[LevelMessages.error];
```

But this one still prints every time a test starts:
```
[🌎 Easy Localization] [DEBUG] Localization initialized
```

Is there a way to hide that one?

**Comment by acoutts** [comment]
Ok I found how to reproduce the issue. The issue is if you try to reference a key that doesn't exist, and that key has a period in it.

```dart
      test('won\'t fail for missing key with consecutive dots', () {
        expect(
          Localization.instance.tr('Processing.'),
          'Processing.',
        );
      });
```
```
Exception: Cannot cache a key that is not nested.
package:easy_localization/src/translations.dart 24:7    Translations.getNested
package:easy_localization/src/translations.dart 7:27    Translations.get
package:easy_localization/src/localization.dart 171:35  Localization._resolve
package:easy_localization/src/localization.dart 53:13   Localization.tr
test/easy_localization_test.dart 163:33                 main.<fn>.<fn>.<fn>
```

**Comment by acoutts** [comment]
Yeah this is tough. I don't think you can figure out if the user is using
* nested keys `welcome_screen.password.title`
* sentences `Hello. Welcome to the app`
* nested sentences `welcome_screen.Welcome to the app`
etc

**Comment by acoutts** [comment]
I was able to fix the logic so it won't fail on missing keys with periods, and all of the tests are passing including the shared preferences null error. I had to put `SharedPreferences.setMockInitialValues({});` before `await EasyLocalization.ensureInitialized();`.

I created this PR to put the changes into your branch: https://github.com/aissat/easy_localization/pull/341

**Comment by aissat** [comment]
@acoutts nice work :+1:

**Comment by acoutts** [comment]
Thanks! Love this package, glad I could help.

> Yeah this is tough. I don't think you can figure out if the user is using
> 
> * nested keys `welcome_screen.password.title`
> * sentences `Hello. Welcome to the app`
> * nested sentences `welcome_screen.Welcome to the app`
>   etc

This is the only head scratcher. I almost think the user needs to give a hint here what kind of key they are using.

**Comment by aissat** [comment]
> Thanks! Love this package, glad I could help.
> 
> > Yeah this is tough. I don't think you can figure out if the user is using
> > 
> > * nested keys `welcome_screen.password.title`
> > * sentences `Hello. Welcome to the app`
> > * nested sentences `welcome_screen.Welcome to the app`
> >   etc
> 
> This is the only head scratcher. I almost think the user needs to give a hint here what kind of key they are using.

thnx @acoutts ,  welcome anytime

**Review by Overman775 — APPROVED** [review]

**Pull request merged**
