### PR TITLE
Add Fallback translations support

### PR DESCRIPTION
**Pull request by xurei**
Add the property `useFallbackTranslations` in EasyLocalization to use the fallback locale keys if a key is missing.
See also issue #239

### CODE REVIEW

**Comment by aissat** [comment]
> Add the property `useFallbackTranslations` in EasyLocalization to use the fallback locale keys if a key is missing.
> See also issue #239

@xurei  nice work :+1:

**Comment by Overman775** [comment]
@xurei  thanks for PR, please resolver merge conflicts

**Review by aissat — APPROVED** [review]

**Comment by xurei** [comment]
@Overman775 Done !

**Comment by Overman775** [comment]
@xurei  please add a few words to readme and changelog, if you have time 😉 

read me:
.....
⚡ Supports plural, gender, nesting, RTL locales and more
↩️ Fallback locale keys redirection
....

changelog: 
[3.0.0]
.....
- Support fallback locale keys redirection

**Review by Overman775 — APPROVED** [review]
@xurei its helpful feature 💯, thank for support project

**Pull request merged**
