### PR TITLE
Add `translate` BuildContext extension

### LINKED ISSUE #433: Can't localize constant widgets
This **example** code would never rebuild:

```dart
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: darkBlue,
      ),
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Center(
          child: const MyWidget(), // If I remove the "const" here, it'll work
        ),
      ),
    );
  }
}

class MyWidget extends StatelessWidget {
  const MyWidget();
  
  @override
  Widget build(BuildContext context) {
    return Text(
      'Hello, World!'.tr(),
      style: Theme.of(context).textTheme.headline4,
    );
  }
}
```

Any way to avoid that?

My main problem with that is that I can only detect this during in runtime. There is any way to make it a compile time error or something like that? I want flutter to know that this widget can't be a constant one, or else the localization will fail.

### PR DESCRIPTION
**Pull request by DartAndrik**
In order to close [Can't localize constant widgets](https://github.com/aissat/easy_localization/issues/433) i think that add `translate` BuildContext extension to public extensions can be the simple solution.

### CODE REVIEW

**Comment by DartAndrik** [comment]
@aissat Hi, could you please take a look on this solution? Of course if you have a bit time.

**Comment by aissat** [comment]
> @aissat Hi, could you please take a look on this solution? Of course if you have a bit time.

I took a look at your code, and it looks like nice work. I like it! However, it would need some small changes like rename `translate` to `tr`  . Overall, great job! :100:

**Comment by DartAndrik** [comment]
> > @aissat Hi, could you please take a look on this solution? Of course if you have a bit time.
> 
> I took a look at your code, and it looks like nice work. I like it! However, it would need some small changes like rename `translate` to `tr` . Overall, great job! 💯

Sure, done.

**Comment by DartAndrik** [comment]
@aissat Hmm. Looks like `easy_localization_loader` package also requires some updates. I see that `flutter pub get` for `example` project failing. And the best solution is update `easy_localization_loader` package before this merge. I probably could help you with that if you don't going to do that by yourself and interested in `easy_localization_loader` support. As a temp solution i commented this dependency for the `example` project.

**Comment by DartAndrik** [comment]
Just don't give up.  :) To meet analysis requirements I refactored inner package - `easy_logger`. It still looks the same but its default logger function will work only for debug mode. And, i see that `easy_logger` was published and maybe the separation of `easy_logger` and `easy_localization` is the worth idea to avoid such cases in future.

**Pull request merged**
