### PR TITLE
Expose components to allow translating without context

### PR DESCRIPTION
**Pull request by jonasN5**
Solves #210.

### CODE REVIEW

**Comment by Overman775** [comment]
@themadmrj this PR contain only export changes... its solve #210?

**Comment by jonasN5** [comment]
Combined with my comment, yes.

**Comment by zmeid** [comment]
Will that PR be merged?

**Comment by nkulic** [comment]
Why is Test and Publish check failing? This is a great feature when wanting to use translation for text outside UI logic, for instance in services logic which does not have access to context (unless explicitly passed which is not convenient)

**Comment by bw-flagship** [comment]
To make the tests work, I suppose some import statements need to be removed since they are redundant now.

**Comment by bw-flagship** [comment]
Closing because abandoned

**Pull request closed without merging**
