### PR TITLE
Fix fallbackLocale, get locale from device, check locale witout countryCode, saveLocale trigger

### PR DESCRIPTION
**Pull request by Overman775**
1. Fix my issue #86 .
2. Right metod to get device locale.
3. Fix bug in check locale when we have only language code in locale.
4. And helpful saveLocale trigger.

### CODE REVIEW

**Comment by Overman775** [comment]
The problem is in the tests, I do not have enough experience to fix an errors in test...

**Comment by aissat** [comment]
@Overman775 plz Crete new PR into develop branch

**Comment by Overman775** [comment]
Ok

**Comment by aissat** [comment]
> Ok

i do it

**Comment by aissat** [comment]
@Overman775
its done

**Pull request closed without merging**
