### PR TITLE
Write nested keys as nested objects

### LINKED ISSUE #390: Keep the nested structure when the LocaleKeys are generated
Let's say I have this `en.json` file:

```json
{
  "project": {
    "name" : "project name",
    "date": "project date"
  },
  "user": {
    "name": "user name",
    "age": "age",
  }
}
```

Right now, running `flutter pub run easy_localization:generate -f keys -o locale_keys.g.dart` to generate the keys will flatten the nested structure and generate:

```dart
LocaleKeys.project_name;
LocaleKeys.project_date;
LocaleKeys.user_name;
LocaleKeys.user_age;
```

---

It would be nice if it could keep the nested structure and generate nested objects:

```dart
LocaleKeys.project.name;
LocaleKeys.project.date;
LocaleKeys.user.name;
LocaleKeys.user.age;
```

### PR DESCRIPTION
**Pull request by TarekkMA**
Fixes: #390

I had to add a method that gets the object value `String val() => 'gender';` to get around the previous behavior where gender/plural objects has other objects inside also.

I'm open to any changes.

### CODE REVIEW

**Comment by bw-flagship** [comment]
@TarekkMA  sorry that nobody reviewed here. If you are still willing to put work in this, please update your branch (maybe update the readme) and I will review

**Comment by TarekkMA** [comment]
@bw-flagship Thank you for your comment, I've changed `val` method to be `key` getter instead. Also I've added `toString` method so users can use "${LocalKeys.test3.test1}" and have it evaluate the key.

### Input:
```json
{
  "test1": "a",
  "test2": "hello",
  "test3": {
    "test1": "z",
    "test2": {
      "test1": "a"
    }
  },
  "test": "اختبار",
  "day": {
    "zero": "{} يوم",
    "one": "{} يوم",
    "two": "{} أيام",
    "few": "{} أيام",
    "many": "{} يوم",
    "other": "{} يوم"
  }
}
```

### Previous output:
```dart
// DO NOT EDIT. This is code generated via package:easy_localization/generate.dart

abstract class  LocaleKeys {
  static const test1 = 'test1';
  static const test2 = 'test2';
  static const test3_test1 = 'test3.test1';
  static const test3_test2_test1 = 'test3.test2.test1';
  static const test3_test2 = 'test3.test2';
  static const test3 = 'test3';
  static const test = 'test';
  static const day = 'day';

}
```


### New output:
```dart
// DO NOT EDIT. This is code generated via package:easy_localization/generate.dart

abstract class LocaleKeys {
  static const test1 = 'test1';
  static const test2 = 'test2';
  static const test3 = _test3();
  static const test = 'test';
  static const day = 'day';
}

class _test3 {
  const _test3();
  String get key => 'test3';
  @override
  String toString() => 'test3';
  final test1 = 'test3.test1';
  final test2 = const _test3_test2();
}

class _test3_test2 {
  const _test3_test2();
  String get key => 'test3.test2';
  @override
  String toString() => 'test3.test2';
  final test1 = 'test3.test2.test1';
}
```

**Comment by bw-flagship** [comment]
@TarekkMA Thanks for updating the branch and explaining the idea.
I'm a big fan and think that the nested stucture is better than the previous one, especially regarding autocomplete.

However, it is a huge breaking change because people would need to switch from

`LocaleKeys.test1_test2`

to 

`LocalKeys.test1.test2`

For my apps, it would be thousands of changes.

I would suggest to "save" it for the next big version (4.0.0) and document the breaking change properly then.
What do you think?

**Comment by TarekkMA** [comment]
I agree this is a breaking change; we need to have it in v4, and I can explore if I can write a simple migration tool, so moving to it would be a minimal manual change.

**Comment by bw-flagship** [comment]
@aissat I created the branch future-releases/v4.0. There we can keep approved features that are too breaking to release them in 3.0. This way, people can use those features already if they want via github references in pubspec.yml.

**Comment by bw-flagship** [comment]
@TarekkMA It seems like there are some linter problems that prevent a merge. Also, could you add a small section in the changelog to describe migrating to the new style?
Thanks!

**Pull request merged**
