### PR TITLE
[pub] Adjust cicd pipeline

### LINKED ISSUE #584: pub.dev authentication is broken
The release pipeline failed with the following text:

```
OAuth2 authorization failed (Bad Request).
Pub needs your authorization to upload packages on your behalf.
In a web browser, go to https://accounts.google.com/o/oauth2/auth?access_type=offline&approval_prompt=force&response_type=code&client_id=818368855108-8grd2eg9tj9f38os6f1urbcvsq399u8n.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A41601&code_challenge=5cDWa23PnYCfadLCGjJHrsRy9Z9oWDBGY-4YwvZLoEE&code_challenge_method=S256&scope=openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email
Then click "Allow access".
```

Pipeline run:
https://github.com/aissat/easy_localization/actions/runs/4971561355/jobs/8896196908

@aissat I think you have to renew the github secrets, only you can do it, thanks!

### PR DESCRIPTION
**Pull request by bw-flagship**
Fixes #584 

- Made the authentication according to https://dart.dev/tools/pub/automated-publishing
- Switched to the stable flutter channel

### CODE REVIEW

**Comment by bw-flagship** [comment]
I could not test the deployment part, but I suppose it should work.

**Review by aissat — APPROVED** [review]

**Comment by aissat** [comment]
> I could not test the deployment part, but I suppose it should work.
great :100:

**Comment by rolandtolnay** [comment]
@bw-flagship Any chance we can merge this now that its approved? 😁

**Comment by bw-flagship** [comment]
@rolandtolnay There is a new problem with the pipeline. If you need a quick fix, you can depend on the commit directly:

```
easy_localization:
    git:
      url: https://github.com/aissat/easy_localization.git
      ref: fa92405
```

**Pull request merged**
