### PR TITLE
Flatten json files the right way.

### PR DESCRIPTION
**Pull request by dodaithach**
Given this json data.
```
{
  "text_fields": {
    "hints": {
      "hint_1": "This is hint 1",
      "hint_2": "This is hint 2"
    },
    "labels": {
      "label_1": "This is label 1",
      "label_2": "This is label 2"
    }
  }
}
```
The current generated code is not reflecting the whole path from the root to leaf elements, which is not good.
```
abstract class  LocaleKeys {
  static const hints_hint_1 = 'hints.hint_1';
  static const hints_hint_2 = 'hints.hint_2';
  static const text_fields_hints = 'text_fields.hints';
  static const labels_label_1 = 'labels.label_1';
  static const labels_label_2 = 'labels.label_2';
  static const text_fields_labels = 'text_fields.labels';
  static const text_fields = 'text_fields';
}
```
After updating, the output is as follow.
```
abstract class  LocaleKeys {
  static const text_fields_hints_hint_1 = 'text_fields.hints.hint_1';
  static const text_fields_hints_hint_2 = 'text_fields.hints.hint_2';
  static const text_fields_labels_label_1 = 'text_fields.labels.label_1';
  static const text_fields_labels_label_2 = 'text_fields.labels.label_2';
}
```

### CODE REVIEW

**Comment by dodaithach** [comment]
Two question:
- What was the source file?
- What keys are considered important?

**Comment by dodaithach** [comment]
Updated @aissat.

**Comment by Overman775** [comment]
> @Overman775 plz check this
> @dodaithach nice 👍

Check today

**Comment by Overman775** [comment]
@dodaithach and please put new generated locale_keys.g.dart in example

**Pull request merged**
